title: Авиация
description: Описание авиационного проекта
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Репозитарий шаблона: https://github.com/just-the-docs/just-the-docs-template
